name: 'Composite Action for Setup'
description: 'Setups JDK and copies secrets'

inputs:
  java-version:
    description: 'Java version to setup'
    required: true
    default: '11'
  occupy-secret:
    description: 'Secret to copy'
    required: true
  occupy-pem:
    description: 'PEM secret'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'zulu'
    - name: Copy Secret
      run: |
        echo ${{ inputs.occupy-secret }} | base64 --decode > Server/src/main/resources/application-secret.yml
      shell: bash
    - name: Copy PEM
      run: |
        echo "${{ inputs.occupy-pem }}" > Server/src/main/resources/prometheus.pem
        chmod 400 Server/src/main/resources/prometheus.pem
      shell: bash
